/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWebsiteRouteImport } from './routes/_authenticated/website'
import { Route as AuthenticatedTrafficSourcesRouteImport } from './routes/_authenticated/traffic-sources'
import { Route as AuthenticatedTopPagesRouteImport } from './routes/_authenticated/top-pages'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedInsightsRouteImport } from './routes/_authenticated/insights'
import { Route as AuthenticatedGeographyRouteImport } from './routes/_authenticated/geography'
import { Route as AuthenticatedEventsRouteImport } from './routes/_authenticated/events'
import { Route as AuthenticatedDevicesRouteImport } from './routes/_authenticated/devices'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAppAnalyticsRouteImport } from './routes/_authenticated/app-analytics'
import { Route as ApiPublicHooksSyncDailyPlayRouteImport } from './routes/api/public/hooks/sync-daily-play'
import { Route as ApiPublicHooksSyncDailyRouteImport } from './routes/api/public/hooks/sync-daily'
import { Route as ApiPublicOauthGoogleStartRouteImport } from './routes/api/public/oauth/google/start'
import { Route as ApiPublicOauthGoogleCallbackRouteImport } from './routes/api/public/oauth/google/callback'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWebsiteRoute = AuthenticatedWebsiteRouteImport.update({
  id: '/website',
  path: '/website',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTrafficSourcesRoute =
  AuthenticatedTrafficSourcesRouteImport.update({
    id: '/traffic-sources',
    path: '/traffic-sources',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTopPagesRoute = AuthenticatedTopPagesRouteImport.update({
  id: '/top-pages',
  path: '/top-pages',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInsightsRoute = AuthenticatedInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGeographyRoute = AuthenticatedGeographyRouteImport.update({
  id: '/geography',
  path: '/geography',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEventsRoute = AuthenticatedEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDevicesRoute = AuthenticatedDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppAnalyticsRoute =
  AuthenticatedAppAnalyticsRouteImport.update({
    id: '/app-analytics',
    path: '/app-analytics',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicHooksSyncDailyPlayRoute =
  ApiPublicHooksSyncDailyPlayRouteImport.update({
    id: '/api/public/hooks/sync-daily-play',
    path: '/api/public/hooks/sync-daily-play',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSyncDailyRoute = ApiPublicHooksSyncDailyRouteImport.update({
  id: '/api/public/hooks/sync-daily',
  path: '/api/public/hooks/sync-daily',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOauthGoogleStartRoute =
  ApiPublicOauthGoogleStartRouteImport.update({
    id: '/api/public/oauth/google/start',
    path: '/api/public/oauth/google/start',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicOauthGoogleCallbackRoute =
  ApiPublicOauthGoogleCallbackRouteImport.update({
    id: '/api/public/oauth/google/callback',
    path: '/api/public/oauth/google/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/app-analytics': typeof AuthenticatedAppAnalyticsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/devices': typeof AuthenticatedDevicesRoute
  '/events': typeof AuthenticatedEventsRoute
  '/geography': typeof AuthenticatedGeographyRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/top-pages': typeof AuthenticatedTopPagesRoute
  '/traffic-sources': typeof AuthenticatedTrafficSourcesRoute
  '/website': typeof AuthenticatedWebsiteRoute
  '/api/public/hooks/sync-daily': typeof ApiPublicHooksSyncDailyRoute
  '/api/public/hooks/sync-daily-play': typeof ApiPublicHooksSyncDailyPlayRoute
  '/api/public/oauth/google/callback': typeof ApiPublicOauthGoogleCallbackRoute
  '/api/public/oauth/google/start': typeof ApiPublicOauthGoogleStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/app-analytics': typeof AuthenticatedAppAnalyticsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/devices': typeof AuthenticatedDevicesRoute
  '/events': typeof AuthenticatedEventsRoute
  '/geography': typeof AuthenticatedGeographyRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/top-pages': typeof AuthenticatedTopPagesRoute
  '/traffic-sources': typeof AuthenticatedTrafficSourcesRoute
  '/website': typeof AuthenticatedWebsiteRoute
  '/api/public/hooks/sync-daily': typeof ApiPublicHooksSyncDailyRoute
  '/api/public/hooks/sync-daily-play': typeof ApiPublicHooksSyncDailyPlayRoute
  '/api/public/oauth/google/callback': typeof ApiPublicOauthGoogleCallbackRoute
  '/api/public/oauth/google/start': typeof ApiPublicOauthGoogleStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/app-analytics': typeof AuthenticatedAppAnalyticsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/devices': typeof AuthenticatedDevicesRoute
  '/_authenticated/events': typeof AuthenticatedEventsRoute
  '/_authenticated/geography': typeof AuthenticatedGeographyRoute
  '/_authenticated/insights': typeof AuthenticatedInsightsRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/top-pages': typeof AuthenticatedTopPagesRoute
  '/_authenticated/traffic-sources': typeof AuthenticatedTrafficSourcesRoute
  '/_authenticated/website': typeof AuthenticatedWebsiteRoute
  '/api/public/hooks/sync-daily': typeof ApiPublicHooksSyncDailyRoute
  '/api/public/hooks/sync-daily-play': typeof ApiPublicHooksSyncDailyPlayRoute
  '/api/public/oauth/google/callback': typeof ApiPublicOauthGoogleCallbackRoute
  '/api/public/oauth/google/start': typeof ApiPublicOauthGoogleStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/app-analytics'
    | '/dashboard'
    | '/devices'
    | '/events'
    | '/geography'
    | '/insights'
    | '/projects'
    | '/reports'
    | '/settings'
    | '/team'
    | '/top-pages'
    | '/traffic-sources'
    | '/website'
    | '/api/public/hooks/sync-daily'
    | '/api/public/hooks/sync-daily-play'
    | '/api/public/oauth/google/callback'
    | '/api/public/oauth/google/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/app-analytics'
    | '/dashboard'
    | '/devices'
    | '/events'
    | '/geography'
    | '/insights'
    | '/projects'
    | '/reports'
    | '/settings'
    | '/team'
    | '/top-pages'
    | '/traffic-sources'
    | '/website'
    | '/api/public/hooks/sync-daily'
    | '/api/public/hooks/sync-daily-play'
    | '/api/public/oauth/google/callback'
    | '/api/public/oauth/google/start'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/app-analytics'
    | '/_authenticated/dashboard'
    | '/_authenticated/devices'
    | '/_authenticated/events'
    | '/_authenticated/geography'
    | '/_authenticated/insights'
    | '/_authenticated/projects'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/team'
    | '/_authenticated/top-pages'
    | '/_authenticated/traffic-sources'
    | '/_authenticated/website'
    | '/api/public/hooks/sync-daily'
    | '/api/public/hooks/sync-daily-play'
    | '/api/public/oauth/google/callback'
    | '/api/public/oauth/google/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  ApiPublicHooksSyncDailyRoute: typeof ApiPublicHooksSyncDailyRoute
  ApiPublicHooksSyncDailyPlayRoute: typeof ApiPublicHooksSyncDailyPlayRoute
  ApiPublicOauthGoogleCallbackRoute: typeof ApiPublicOauthGoogleCallbackRoute
  ApiPublicOauthGoogleStartRoute: typeof ApiPublicOauthGoogleStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/website': {
      id: '/_authenticated/website'
      path: '/website'
      fullPath: '/website'
      preLoaderRoute: typeof AuthenticatedWebsiteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/traffic-sources': {
      id: '/_authenticated/traffic-sources'
      path: '/traffic-sources'
      fullPath: '/traffic-sources'
      preLoaderRoute: typeof AuthenticatedTrafficSourcesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/top-pages': {
      id: '/_authenticated/top-pages'
      path: '/top-pages'
      fullPath: '/top-pages'
      preLoaderRoute: typeof AuthenticatedTopPagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/insights': {
      id: '/_authenticated/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthenticatedInsightsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/geography': {
      id: '/_authenticated/geography'
      path: '/geography'
      fullPath: '/geography'
      preLoaderRoute: typeof AuthenticatedGeographyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/events': {
      id: '/_authenticated/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AuthenticatedEventsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/devices': {
      id: '/_authenticated/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof AuthenticatedDevicesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app-analytics': {
      id: '/_authenticated/app-analytics'
      path: '/app-analytics'
      fullPath: '/app-analytics'
      preLoaderRoute: typeof AuthenticatedAppAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/hooks/sync-daily-play': {
      id: '/api/public/hooks/sync-daily-play'
      path: '/api/public/hooks/sync-daily-play'
      fullPath: '/api/public/hooks/sync-daily-play'
      preLoaderRoute: typeof ApiPublicHooksSyncDailyPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-daily': {
      id: '/api/public/hooks/sync-daily'
      path: '/api/public/hooks/sync-daily'
      fullPath: '/api/public/hooks/sync-daily'
      preLoaderRoute: typeof ApiPublicHooksSyncDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oauth/google/start': {
      id: '/api/public/oauth/google/start'
      path: '/api/public/oauth/google/start'
      fullPath: '/api/public/oauth/google/start'
      preLoaderRoute: typeof ApiPublicOauthGoogleStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oauth/google/callback': {
      id: '/api/public/oauth/google/callback'
      path: '/api/public/oauth/google/callback'
      fullPath: '/api/public/oauth/google/callback'
      preLoaderRoute: typeof ApiPublicOauthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAppAnalyticsRoute: typeof AuthenticatedAppAnalyticsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDevicesRoute: typeof AuthenticatedDevicesRoute
  AuthenticatedEventsRoute: typeof AuthenticatedEventsRoute
  AuthenticatedGeographyRoute: typeof AuthenticatedGeographyRoute
  AuthenticatedInsightsRoute: typeof AuthenticatedInsightsRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedTopPagesRoute: typeof AuthenticatedTopPagesRoute
  AuthenticatedTrafficSourcesRoute: typeof AuthenticatedTrafficSourcesRoute
  AuthenticatedWebsiteRoute: typeof AuthenticatedWebsiteRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppAnalyticsRoute: AuthenticatedAppAnalyticsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDevicesRoute: AuthenticatedDevicesRoute,
  AuthenticatedEventsRoute: AuthenticatedEventsRoute,
  AuthenticatedGeographyRoute: AuthenticatedGeographyRoute,
  AuthenticatedInsightsRoute: AuthenticatedInsightsRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedTopPagesRoute: AuthenticatedTopPagesRoute,
  AuthenticatedTrafficSourcesRoute: AuthenticatedTrafficSourcesRoute,
  AuthenticatedWebsiteRoute: AuthenticatedWebsiteRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  ApiPublicHooksSyncDailyRoute: ApiPublicHooksSyncDailyRoute,
  ApiPublicHooksSyncDailyPlayRoute: ApiPublicHooksSyncDailyPlayRoute,
  ApiPublicOauthGoogleCallbackRoute: ApiPublicOauthGoogleCallbackRoute,
  ApiPublicOauthGoogleStartRoute: ApiPublicOauthGoogleStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
